"""
Track A3 — the backend asserted against EXTERNAL ground truth.

`parity/*.json` proves the two engines agree; it cannot prove either is right,
because `gen_parity_vectors.py` writes the backend's own output and so makes
the backend an unfalsifiable oracle. A backend regression regenerates the
vectors and CI stays green.

`parity/anchors/` breaks that circle: values published outside this repository,
checked in, never regenerated by anything here. This suite asserts the BACKEND
against them. `packages/astra-core/test/anchors.test.ts` asserts the TS engine
against the same files independently — neither engine is the other's reference
here, which is the whole point.

Tolerance is `uncertainty + engine_allowance`, both read from the anchor
record. Widening either is an anchor change and trips the CI guard.
"""
import json
import os
import re
import sys
from pathlib import Path

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import swisseph as swe  # noqa: E402

# `set_sid_mode` is process-global C state. The suite is single-threaded today,
# so this is largely ceremonial — but it is the app's own lock, and reaching for
# it here documents that the ayanamsa calls below are frame-sensitive in exactly
# the way ephemeris.py's comment describes.
from ephemeris import swe_lock  # noqa: E402

# Deliberately the app's OWN body table and longitude flags, private names and
# all, rather than a reimplementation. A test that rebuilt these would keep
# passing if the application's flags drifted — which is precisely the drift most
# worth catching, since FLG_SWIEPH vs FLG_MOSEPH silently changes which
# ephemeris answers, and the frame flags decide whether the number is even
# comparable to the anchor.
from ephemeris import _FLG_LON, _PLANET_TABLE  # noqa: E402

# Same argument for the eclipse side: the app's own eclipse flags and its own
# retflag->name mapping. _eclipse_nature is the function a reader's "total" or
# "penumbral" actually comes from, so anchoring it is anchoring the product.
from predictive import _FLAGS_ECL, _eclipse_nature  # noqa: E402

ANCHOR_DIR = Path(__file__).resolve().parents[2] / "parity" / "anchors"
DELTA_T_FILE = ANCHOR_DIR / "delta_t.json"
AYANAMSA_FILE = ANCHOR_DIR / "ayanamsa.json"
LONGITUDES_FILE = ANCHOR_DIR / "planet_longitudes.json"
ECLIPSES_FILE = ANCHOR_DIR / "eclipses.json"


def _angular_sep(a: float, b: float) -> float:
    """Separation of two ecliptic longitudes, honouring the 0/360 seam.

    A plain abs(a - b) reports ~360° for two positions a hair either side of
    Aries 0°, which would fail an anchor that is in fact exact — and the Moon
    crosses that seam every month, so this is a routine case rather than an
    edge one.
    """
    d = abs(a - b) % 360.0
    return min(d, 360.0 - d)


def _load(path: Path):
    if not path.exists():
        pytest.skip(f"{path.name} not acquired yet — see parity/anchors/ACQUISITION.md")
    return json.loads(path.read_text())


# --------------------------------------------------------------------------- #
# ΔT — the time base under every position in both engines
# --------------------------------------------------------------------------- #

_DELTA_T = _load(DELTA_T_FILE) if DELTA_T_FILE.exists() else {"anchors": []}


@pytest.mark.parametrize(
    "anchor", _DELTA_T["anchors"], ids=lambda a: a["id"]
)
def test_delta_t_matches_published_value(anchor):
    """swe.deltat() must reproduce the published ΔT within the source's own
    uncertainty plus the declared engine allowance.

    This is the fault class the golden vectors are structurally blind to: a
    wrong ΔT moves every body in BOTH engines identically, so they keep
    agreeing with each other while both drift away from the sky.
    """
    # swe.deltat returns DAYS; the anchor is published in seconds.
    actual = swe.deltat(anchor["jd_ut"]) * 86400.0
    tol = anchor["uncertainty"] + anchor["engine_allowance"]
    delta = abs(actual - anchor["value"])
    assert delta <= tol, (
        f"{anchor['id']}: engine {actual:.4f} s vs published {anchor['value']} s "
        f"(Δ{delta:.4f} s > {tol} s tolerance)\n"
        f"  source: {anchor['source']}\n"
        f"  {anchor['url']}\n"
        "  Do NOT widen the anchor to make this pass — see parity/anchors/README.md."
    )


def test_delta_t_rate_between_anchors():
    """Two ΔT points a year apart also pin the table's SLOPE.

    A constant offset bug and a rate bug both move a single point; only the
    pair separates them. Guarded so it degrades to a skip rather than an
    error if the anchor set is ever reduced to one point.
    """
    by_id = {a["id"]: a for a in _DELTA_T["anchors"]}
    start, end = by_id.get("deltat-2000-01-01"), by_id.get("deltat-2000-12-31")
    if not (start and end):
        pytest.skip("both 2000 ΔT anchors required for the rate check")

    published_rate = end["value"] - start["value"]
    engine_rate = (swe.deltat(end["jd_ut"]) - swe.deltat(start["jd_ut"])) * 86400.0
    # Each endpoint carries its own uncertainty; a difference carries both.
    tol = sum(a["uncertainty"] + a["engine_allowance"] for a in (start, end))
    assert abs(engine_rate - published_rate) <= tol, (
        f"ΔT drift across 2000: engine {engine_rate:+.4f} s vs published "
        f"{published_rate:+.4f} s (tolerance ±{tol} s)"
    )


# --------------------------------------------------------------------------- #
# Planetary longitudes — where the engine actually puts a body
# --------------------------------------------------------------------------- #

_LONGITUDES = _load(LONGITUDES_FILE) if LONGITUDES_FILE.exists() else {"anchors": []}
_SWE_ID = {name: swe_id for name, swe_id, _ in _PLANET_TABLE}


def test_longitude_anchor_frame_is_of_date():
    """Assert the FRAME before asserting any value.

    ACQUISITION.md §1 calls this the frame trap: an anchor pulled in the J2000
    ecliptic instead of the ecliptic of date is wrong by up to ~1.4°/century of
    precession — two to three degrees at this file's 1800 and 2100 epochs. It
    fails as a smooth trend across epochs rather than as noise, which reads
    convincingly like an engine bug and would send someone hunting in the wrong
    place. Cheap to assert, expensive to debug.
    """
    if not _LONGITUDES["anchors"]:
        pytest.skip("planet_longitudes.json not acquired — see ACQUISITION.md")
    assert re.search(r"of date", _LONGITUDES.get("frame", ""), re.I), (
        "anchor frame must be the true ecliptic and equinox OF DATE — the frame "
        "swe_calc_ut returns. See ACQUISITION.md §Frame trap."
    )


@pytest.mark.parametrize("anchor", _LONGITUDES["anchors"], ids=lambda a: a["id"])
def test_planet_longitude_matches_published_ephemeris(anchor):
    """swe.calc_ut must put each body where JPL Horizons puts it.

    This is the first anchor in the directory that constrains a POSITION. ΔT
    pins the clock and ayanamsa.json pins the sidereal rotation, but neither
    says where a planet is. Nothing inside the repository can: the golden
    vectors are generated from the backend's own output, and the property
    harness compares the two engines to each other — both stay green if both
    are wrong together, which is a live risk now that both sit on Swiss.
    """
    swe_id = _SWE_ID.get(anchor["body"])
    assert swe_id is not None, (
        f"{anchor['id']}: {anchor['body']} is not in the app's _PLANET_TABLE"
    )
    with swe_lock:
        values, _ = swe.calc_ut(anchor["jd_ut"], swe_id, _FLG_LON)
    actual = values[0]
    tol = anchor["uncertainty"] + anchor["engine_allowance"]
    delta = _angular_sep(actual, anchor["value"])
    assert delta <= tol, (
        f"{anchor['id']}: engine {actual:.7f}° vs published {anchor['value']}° "
        f"(Δ{delta * 3600:.3f}\" > {tol * 3600:.3f}\" tolerance)\n"
        f"  frame:  {_LONGITUDES.get('frame', '?')[:60]}...\n"
        f"  source: {anchor['source']}\n"
        f"  {anchor['url']}\n"
        "  A miss that GROWS with distance from 2000 is a frame error, not a\n"
        "  position error — check the frame assertion above first.\n"
        "  Do NOT widen the anchor to make this pass — see parity/anchors/README.md."
    )


# --------------------------------------------------------------------------- #
# Ayanamsa — the sidereal frame's single degree of freedom
# --------------------------------------------------------------------------- #

_AYANAMSA = _load(AYANAMSA_FILE) if AYANAMSA_FILE.exists() else {"anchors": []}


def _ayanamsa_deg(jd_tt: float, frame: str) -> float:
    """Swiss Ephemeris' Lahiri ayanamsa at a TT instant, in the requested frame.

    Two things here are deliberate and both are frame decisions, not style:

    `FLG_NONUT` is what separates MEAN from TRUE. Without it Swiss returns the
    TRUE ayanamsa, which differs from the mean by nutation in longitude — up to
    ~17 arcsec, an order of magnitude larger than any tolerance in this file.
    The two anchors genuinely differ in frame because their sources do, so the
    flag is chosen per anchor rather than fixed here; a comparison that picked
    the wrong one would fail confidently while both engine and anchor were right.

    `get_ayanamsa_ex` (not `..._ex_ut`) takes a TT argument, matching the
    anchors' `jd_tt`. Going through the UT variant would apply ΔT twice over —
    negligible at J2000 (~1e-4 arcsec), less so the further out an anchor sits.
    """
    if frame not in ("mean", "true"):
        raise ValueError(
            f"unknown ayanamsa frame {frame!r} — the anchor's `frame` field must "
            "be 'mean' or 'true'. Guessing here is how a 17 arcsec nutation error "
            "gets mistaken for an engine bug."
        )
    flags = swe.FLG_NONUT if frame == "mean" else 0
    with swe_lock:
        swe.set_sid_mode(swe.SIDM_LAHIRI, 0, 0)
        out = swe.get_ayanamsa_ex(jd_tt, flags)
    # pyswisseph has returned both a bare float and a (retflag, ayanamsa) tuple
    # across versions; the repo pins 2.10 but the suite should not break on a
    # bump that only changes the wrapper's shape.
    return float(out[1]) if isinstance(out, (tuple, list)) else float(out)


@pytest.mark.parametrize("anchor", _AYANAMSA["anchors"], ids=lambda a: a["id"])
def test_ayanamsa_matches_published_value(anchor):
    """swe must reproduce the published Lahiri ayanamsa within the declared window.

    This is a rigid-rotation fault class. An ayanamsa error moves every body in
    a sidereal chart by exactly the same angle, so every aspect, pattern and
    inter-body relationship survives intact while signs and houses shift
    wholesale. Both engines rotate together, so the golden vectors stay green
    and the parity harness stays green — nothing inside this repository can see
    it. Only an external value can.
    """
    actual = _ayanamsa_deg(anchor["jd_tt"], anchor["frame"])
    tol = anchor["uncertainty"] + anchor["engine_allowance"]
    delta = abs(actual - anchor["value"])
    assert delta <= tol, (
        f"{anchor['id']}: engine {actual:.7f}° vs published {anchor['value']}° "
        f"(Δ{delta * 3600:.3f}\" > {tol * 3600:.3f}\" tolerance)\n"
        f"  frame:  {anchor['frame']}\n"
        f"  source: {anchor['source']}\n"
        f"  {anchor['url']}\n"
        "  Before touching the anchor, check the FRAME. A miss in the 14-17 arcsec\n"
        "  range is the nutation term — a mean-vs-true mix-up, not an engine error.\n"
        "  See the file's frame_note.\n"
        "  Do NOT widen the anchor to make this pass — see parity/anchors/README.md."
    )


def test_ayanamsa_mean_and_true_differ_by_nutation():
    """Guard the FRAME itself, which is the trap this anchor is most exposed to.

    The anchor is a MEAN value and the assertion above suppresses nutation to
    match it. If a future change swapped the flag — or if a Swiss bump altered
    what `FLG_NONUT` means — the anchor test could keep passing against the
    wrong quantity only if mean and true happened to coincide, which they do
    twice per 18.6-year nutation cycle. Asserting that the two are SEPARATED by
    a plausible nutation at an epoch where nutation is known to be large keeps
    that coincidence from being mistaken for correctness.

    This is engine-vs-engine and so is NOT an anchor assertion; it pins the
    frame, and the anchor pins the value.
    """
    if not _AYANAMSA["anchors"]:
        pytest.skip("no ayanamsa anchors acquired yet")
    jd_tt = _AYANAMSA["anchors"][0]["jd_tt"]
    diff_arcsec = (
        _ayanamsa_deg(jd_tt, "true") - _ayanamsa_deg(jd_tt, "mean")
    ) * 3600.0

    # Nutation in longitude is bounded by roughly ±17.2". At J2000 it is close
    # to −14"; the window is kept wide because this guards a frame, not a value.
    assert 0.5 <= abs(diff_arcsec) <= 20.0, (
        f"mean and true ayanamsa differ by {diff_arcsec:+.3f}\", which is not a "
        "plausible nutation in longitude. Either FLG_NONUT no longer suppresses "
        "nutation in this Swiss build, or both calls are now returning the same "
        "frame — in which case test_ayanamsa_matches_published_value is no longer "
        "checking what it claims to check."
    )


# --------------------------------------------------------------------------- #
# Provenance — the anchors' own contract, enforced
# --------------------------------------------------------------------------- #

ANCHOR_FILES = sorted(ANCHOR_DIR.glob("*.json"))

# Provenance is per-ANCHOR: who published it, where, and the quoted text.
PROVENANCE_FIELDS = ("id", "source", "url", "citation", "retrieved")
# A measurement is one number with its own error budget. In a single-measurement
# file these sit directly on the anchor; in a multi-measurement one (eclipses,
# where the instant and the magnitude are different columns with different
# uncertainties) they sit inside each entry of `measurements`.
MEASUREMENT_FIELDS = (
    "value", "unit", "uncertainty", "uncertainty_basis",
    "engine_allowance", "engine_allowance_note",
)


def _measurements(anchor: dict) -> dict:
    """Every measurement on an anchor, keyed by name, for either file shape.

    Returns {"value": <the anchor itself>} for the flat single-measurement
    form, so callers never branch on the shape.
    """
    if "measurements" in anchor:
        return anchor["measurements"]
    return {"value": anchor}


@pytest.mark.parametrize("path", ANCHOR_FILES, ids=lambda p: p.name)
def test_every_anchor_carries_full_provenance(path):
    """An anchor without provenance is just a number somebody typed.

    The directory's promise is that a third party can re-derive every value
    from its recorded source; that promise is only as good as the weakest
    record, so this is asserted mechanically rather than trusted to review.
    """
    payload = json.loads(path.read_text())
    assert payload.get("schema", "").startswith("astra-parity/anchor-"), (
        f"{path.name}: missing or malformed schema tag"
    )
    for anchor in payload["anchors"]:
        aid = anchor.get("id", "?")
        missing = [f for f in PROVENANCE_FIELDS if f not in anchor]
        assert not missing, f"{path.name}:{aid} missing {missing}"
        assert anchor["url"].startswith("http"), (
            f"{path.name}:{aid} url is not a retrievable reference"
        )
        assert anchor["citation"].strip(), (
            f"{path.name}:{aid} citation is empty — the quoted source "
            "text is what makes the value checkable by a third party"
        )
        measurements = _measurements(anchor)
        assert measurements, f"{path.name}:{aid} carries no measurements at all"
        for name, m in measurements.items():
            gaps = [f for f in MEASUREMENT_FIELDS if f not in m]
            assert not gaps, f"{path.name}:{aid}.{name} missing {gaps}"


@pytest.mark.parametrize("path", ANCHOR_FILES, ids=lambda p: p.name)
def test_anchor_tolerances_stay_bounded(path):
    """A ratchet on the anchors themselves.

    The failure mode this exists for is a future session quietly multiplying
    an `engine_allowance` until a divergence fits inside it. An allowance
    wider than this could hide a chart-visible error, which is the one thing
    an anchor must never do.
    """
    # Keyed by (quantity, unit): a multi-measurement file mixes units, and a
    # single cap across days and dimensionless ratios would be meaningless.
    limits = {
        # 0.5 s of ΔT ≈ 0.27 arcsec of lunar motion — still an order of
        # magnitude below the 0.01° tolerance any chart output is held to.
        ("delta_t_seconds", "s"): 0.5,
        # 1 arcmin: the point at which a longitude error becomes capable of
        # flipping a sign or house assignment.
        ("ecliptic_longitude_deg", "deg"): 1.0 / 60.0,
        # Same 1 arcmin cap, same reason, but it bites harder: the ayanamsa is
        # a rigid rotation, so this error does not average out across a chart —
        # every body carries the full amount in the same direction at once.
        ("ayanamsa_deg", "deg"): 1.0 / 60.0,
        # 120 s, in days. The same 1-arcmin philosophy as the longitude caps,
        # converted through the rate that matters here: the Moon closes on the
        # shadow axis at ~0.5 arcsec/s, so 1 arcmin of lunar motion IS ~120 s of
        # eclipse timing. The widest tolerance in the file today is 10.5 s.
        ("eclipse_circumstances", "jd_tt"): 120.0 / 86400.0,
        # Eclipse magnitude is dimensionless and never reaches a chart, so the
        # 1-arcmin argument does not apply. What it governs is the NATURE
        # boundary, and the binding constraint is the closest any anchor in the
        # file sits to one: lunar-1999-01-31's penumbral magnitude is 1.0027,
        # i.e. 0.0027 above the total-penumbral boundary at 1.0. A cap below
        # that is provably unable to license a tolerance that hides a
        # classification flip. Worst tolerance in the file today is 0.00205.
        ("eclipse_circumstances", "ratio"): 0.0025,
    }
    payload = json.loads(path.read_text())
    quantity = payload["quantity"]
    checked = 0
    for anchor in payload["anchors"]:
        for name, m in _measurements(anchor).items():
            cap = limits.get((quantity, m["unit"]))
            if cap is None:
                continue
            checked += 1
            total = m["uncertainty"] + m["engine_allowance"]
            assert total <= cap, (
                f"{path.name}:{anchor['id']}.{name} tolerance {total} exceeds "
                f"the {cap} {m['unit']} cap for {quantity} — a tolerance this "
                "wide could hide a chart-visible error. Justify it in an ADR "
                "under docs/design/adr/ and raise the cap deliberately, or fix "
                "the engine."
            )
    if checked == 0:
        pytest.skip(f"no declared cap for quantity {quantity}")


# --------------------------------------------------------------------------- #
# Eclipses — the instant, the magnitude, and the classification
# --------------------------------------------------------------------------- #
# `nature` is the only eclipse field a reader ever sees, and until these landed
# nothing in the repo could tell a correct classification from a wrong one: the
# suite simply reported whichever bit Swiss returned. The magnitudes are here
# because magnitude is the quantity the nature boundary is drawn on.
#
# Read eclipses.json's magnitude_convention_note and delta_t_column_note before
# changing anything here. Both encode a comparison that looks obvious and is
# wrong.
#
# Verified to bite, 2026-08-15. Every assertion below sits at <=50% of its
# tolerance, so nothing here passes on slack. Two injected faults were checked:
# reading attr[0] instead of attr[8] fails on 4/4 solar anchors, and a 120 s
# timing bias (1 arcmin of lunar motion) fails on 8/8.
#
# The honest negative, recorded so nobody assumes more coverage than exists:
# converting with the catalog's own predicted ΔT — the mistake delta_t_column_note
# warns about — is NOT caught. It lands at 2.77 s (solar-2017) and 3.32 s
# (lunar-2018) against a 3.50 s tolerance, i.e. 95% on the latter. Comparing in
# TD is therefore what keeps that anchor off a knife-edge rather than something
# these tests enforce; do it the wrong way and the suite goes flaky on the next
# swisseph release instead of going red now.

_ECLIPSES = _load(ECLIPSES_FILE) if ECLIPSES_FILE.exists() else {"anchors": []}
_SOLAR = [a for a in _ECLIPSES["anchors"] if a["kind"] == "solar"]
_LUNAR = [a for a in _ECLIPSES["anchors"] if a["kind"] == "lunar"]

# Days before the published instant to begin the search. Comfortably shorter
# than the ~29.5-day minimum spacing between two eclipses of the same kind, so
# the window cannot select a different eclipse, and far longer than any credible
# engine error, so it is not fitted to the answer either.
_SEARCH_LEAD_DAYS = 15.0


def _engine_td(jd_ut: float) -> float:
    """The engine's UT answer expressed in TD, using the engine's own ΔT.

    The catalog publishes TD; the engine works in UT. Converting THIS direction
    is deliberate — see eclipses.json's delta_t_column_note. The catalog's own
    ΔT column is a pre-2006 extrapolation for anything recent (70 s vs the
    observed 68.85 s at 2017), so using it would charge Espenak's prediction
    error to our engine. ΔT is independently anchored by delta_t.json, so this
    conversion is covered rather than assumed.
    """
    return jd_ut + swe.deltat(jd_ut)


def _tol_days(measurement: dict) -> float:
    return measurement["uncertainty"] + measurement["engine_allowance"]


def _fail(anchor, what, engine, published, tol, unit):
    return (
        f"{anchor['id']}: {what} — engine {engine!r} vs published "
        f"{published!r} (Δ{abs(engine - published):.6g} > {tol:.6g} {unit})\n"
        f"  source: {anchor['source']}\n  {anchor['url']}\n"
        f"  row: {anchor['citation']}\n"
        "  Do NOT widen the anchor to make this pass — see parity/anchors/README.md."
    )


@pytest.mark.parametrize("anchor", _SOLAR, ids=lambda a: a["id"])
def test_solar_eclipse_matches_published_circumstances(anchor):
    """Instant, magnitude and nature of a solar eclipse, against NASA's catalog.

    Uses the application's OWN flags and nature mapping rather than a
    reimplementation: a test that rebuilt these would keep passing if the app's
    eclipse flags drifted, which is precisely the drift worth catching.
    """
    inst = anchor["measurements"]["instant_td"]
    published_td = inst["value"]

    retflag, tret = swe.sol_eclipse_when_glob(
        published_td - _SEARCH_LEAD_DAYS, _FLAGS_ECL, 0, False
    )
    engine_td = _engine_td(tret[0])

    tol = _tol_days(inst)
    assert abs(engine_td - published_td) <= tol, _fail(
        anchor, "instant of greatest eclipse (TD)", engine_td, published_td,
        tol, f"days ({tol * 86400:.1f} s)",
    )

    assert _eclipse_nature(retflag) == anchor["nature"], _fail(
        anchor, "nature", _eclipse_nature(retflag), anchor["nature"], 0, "category"
    )

    # attr[8] is "magnitude acc. to NASA" — attr[0] for a partial, attr[1] for
    # annular/total, which is exactly the catalog's own convention. attr[0]
    # alone disagrees by ~0.03 on a total eclipse, definitionally, not in error.
    mag = anchor["measurements"]["magnitude"]
    _r, _geopos, attr = swe.sol_eclipse_where(tret[0], _FLAGS_ECL)
    tol_m = _tol_days(mag)
    assert abs(attr[8] - mag["value"]) <= tol_m, _fail(
        anchor, "eclipse magnitude", attr[8], mag["value"], tol_m, "ratio"
    )


@pytest.mark.parametrize("anchor", _LUNAR, ids=lambda a: a["id"])
def test_lunar_eclipse_matches_published_circumstances(anchor):
    """Same three assertions through the OTHER Swiss entry point.

    `lun_eclipse_when` is a different search from `sol_eclipse_when_glob`, so a
    solar-only anchor set would leave half of eclipse_timeline unproven.
    """
    inst = anchor["measurements"]["instant_td"]
    published_td = inst["value"]

    retflag, tret = swe.lun_eclipse_when(
        published_td - _SEARCH_LEAD_DAYS, _FLAGS_ECL, 0, False
    )
    engine_td = _engine_td(tret[0])

    tol = _tol_days(inst)
    assert abs(engine_td - published_td) <= tol, _fail(
        anchor, "instant of greatest eclipse (TD)", engine_td, published_td,
        tol, f"days ({tol * 86400:.1f} s)",
    )

    # Covers the 'Nx' total-penumbral and 'T+' central-total sub-types the app
    # deliberately collapses into penumbral/total.
    assert _eclipse_nature(retflag) == anchor["nature"], _fail(
        anchor, "nature", _eclipse_nature(retflag), anchor["nature"], 0, "category"
    )

    # geopos only affects the alt/az entries; attr[0] (umbral) and attr[1]
    # (penumbral) are geocentric. umbral_magnitude is absent for the penumbral
    # anchor on purpose — Swiss clamps it at 0 where the catalog signs it
    # negative, so asserting it would fail forever on a definitional difference.
    _r, attr = swe.lun_eclipse_how(tret[0], [0.0, 0.0, 0.0], _FLAGS_ECL)
    for name, index in (("umbral_magnitude", 0), ("penumbral_magnitude", 1)):
        m = anchor["measurements"].get(name)
        if m is None:
            continue
        tol_m = _tol_days(m)
        assert abs(attr[index] - m["value"]) <= tol_m, _fail(
            anchor, name, attr[index], m["value"], tol_m, "ratio"
        )


def test_penumbral_anchor_does_not_assert_umbral_magnitude():
    """Pin the omission itself, so it cannot be 'helpfully' filled in later.

    lunar-1999-01-31 has no umbral phase. The catalog prints -0.0258 (how far
    the Moon missed the umbra); Swiss clamps to 0.0000. Both are right about
    different questions. Someone adding the catalog's figure to `measurements`
    would produce a test that fails forever and looks like an engine bug, so
    the absence is asserted rather than left to a comment.
    """
    by_id = {a["id"]: a for a in _LUNAR}
    anchor = by_id.get("lunar-1999-01-31")
    if anchor is None:
        pytest.skip("lunar-1999-01-31 anchor not present")
    assert anchor["nature"] == "penumbral"
    assert "umbral_magnitude" not in anchor["measurements"], (
        "lunar-1999-01-31 must NOT anchor an umbral magnitude — see the "
        "umbral_magnitude_omitted note in eclipses.json"
    )


def test_eclipse_timeline_reports_anchored_eclipses_on_the_published_date():
    """Bind the anchors to the PRODUCT surface, not just to Swiss.

    Everything above asserts the engine calls underneath eclipse_timeline. This
    asserts what a reader is actually shown: that the timeline surfaces the
    anchored eclipse, on the published calendar date, with the published
    nature. It is the step that would catch a correct engine wired up wrongly —
    a frame mix-up, an off-by-one in the search loop, a lost nature bit.
    """
    if not _ECLIPSES["anchors"]:
        pytest.skip("eclipses.json not acquired — see ACQUISITION.md")

    import predictive as P  # noqa: PLC0415 — local, keeps module import cheap
    from models import ChartRequest  # noqa: PLC0415

    natal = ChartRequest(year=1879, month=3, day=14, hour=11, minute=30,
                         second=0, lat=48.4011, lng=9.9876, tz_offset=0.67)

    for anchor in _ECLIPSES["anchors"]:
        published_date = anchor["td_instant"][:10]
        # Start a few days before and take enough events to be sure the window
        # covers it regardless of which kind interleaves first.
        start = swe.revjul(anchor["measurements"]["instant_td"]["value"] - 3.0,
                           swe.GREG_CAL)
        start_iso = f"{start[0]:04d}-{start[1]:02d}-{start[2]:02d}"
        timeline = P.eclipse_timeline(natal, start_iso, count=4)

        match = [e for e in timeline.eclipses if e.date == published_date]
        assert match, (
            f"{anchor['id']}: eclipse_timeline starting {start_iso} did not "
            f"report anything on {published_date}; it returned "
            f"{[(e.date, e.kind, e.nature) for e in timeline.eclipses]}"
        )
        event = match[0]
        assert event.kind == anchor["kind"], (
            f"{anchor['id']}: timeline says kind={event.kind}, "
            f"catalog says {anchor['kind']}"
        )
        assert event.nature == anchor["nature"], (
            f"{anchor['id']}: timeline says nature={event.nature}, "
            f"catalog says {anchor['nature']} (row: {anchor['citation']})"
        )
