"""
Track A3 — the backend asserted against EXTERNAL ground truth.

`parity/*.json` proves the two engines agree; it cannot prove either is right,
because `gen_parity_vectors.py` writes the backend's own output and so makes
the backend an unfalsifiable oracle. A backend regression regenerates the
vectors and CI stays green.

`parity/anchors/` breaks that circle: values published outside this repository,
checked in, never regenerated by anything here. This suite asserts the BACKEND
against them. `packages/astra-core/test/anchors.test.ts` asserts the TS engine
against the same files independently — neither engine is the other's reference
here, which is the whole point.

Tolerance is `uncertainty + engine_allowance`, both read from the anchor
record. Widening either is an anchor change and trips the CI guard.
"""
import json
import os
import re
import sys
from pathlib import Path

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import swisseph as swe  # noqa: E402

# `set_sid_mode` is process-global C state. The suite is single-threaded today,
# so this is largely ceremonial — but it is the app's own lock, and reaching for
# it here documents that the ayanamsa calls below are frame-sensitive in exactly
# the way ephemeris.py's comment describes.
from ephemeris import swe_lock  # noqa: E402

# Deliberately the app's OWN body table and longitude flags, private names and
# all, rather than a reimplementation. A test that rebuilt these would keep
# passing if the application's flags drifted — which is precisely the drift most
# worth catching, since FLG_SWIEPH vs FLG_MOSEPH silently changes which
# ephemeris answers, and the frame flags decide whether the number is even
# comparable to the anchor.
from ephemeris import _FLG_LON, _PLANET_TABLE  # noqa: E402

ANCHOR_DIR = Path(__file__).resolve().parents[2] / "parity" / "anchors"
DELTA_T_FILE = ANCHOR_DIR / "delta_t.json"
AYANAMSA_FILE = ANCHOR_DIR / "ayanamsa.json"
LONGITUDES_FILE = ANCHOR_DIR / "planet_longitudes.json"


def _angular_sep(a: float, b: float) -> float:
    """Separation of two ecliptic longitudes, honouring the 0/360 seam.

    A plain abs(a - b) reports ~360° for two positions a hair either side of
    Aries 0°, which would fail an anchor that is in fact exact — and the Moon
    crosses that seam every month, so this is a routine case rather than an
    edge one.
    """
    d = abs(a - b) % 360.0
    return min(d, 360.0 - d)


def _load(path: Path):
    if not path.exists():
        pytest.skip(f"{path.name} not acquired yet — see parity/anchors/ACQUISITION.md")
    return json.loads(path.read_text())


# --------------------------------------------------------------------------- #
# ΔT — the time base under every position in both engines
# --------------------------------------------------------------------------- #

_DELTA_T = _load(DELTA_T_FILE) if DELTA_T_FILE.exists() else {"anchors": []}


@pytest.mark.parametrize(
    "anchor", _DELTA_T["anchors"], ids=lambda a: a["id"]
)
def test_delta_t_matches_published_value(anchor):
    """swe.deltat() must reproduce the published ΔT within the source's own
    uncertainty plus the declared engine allowance.

    This is the fault class the golden vectors are structurally blind to: a
    wrong ΔT moves every body in BOTH engines identically, so they keep
    agreeing with each other while both drift away from the sky.
    """
    # swe.deltat returns DAYS; the anchor is published in seconds.
    actual = swe.deltat(anchor["jd_ut"]) * 86400.0
    tol = anchor["uncertainty"] + anchor["engine_allowance"]
    delta = abs(actual - anchor["value"])
    assert delta <= tol, (
        f"{anchor['id']}: engine {actual:.4f} s vs published {anchor['value']} s "
        f"(Δ{delta:.4f} s > {tol} s tolerance)\n"
        f"  source: {anchor['source']}\n"
        f"  {anchor['url']}\n"
        "  Do NOT widen the anchor to make this pass — see parity/anchors/README.md."
    )


def test_delta_t_rate_between_anchors():
    """Two ΔT points a year apart also pin the table's SLOPE.

    A constant offset bug and a rate bug both move a single point; only the
    pair separates them. Guarded so it degrades to a skip rather than an
    error if the anchor set is ever reduced to one point.
    """
    by_id = {a["id"]: a for a in _DELTA_T["anchors"]}
    start, end = by_id.get("deltat-2000-01-01"), by_id.get("deltat-2000-12-31")
    if not (start and end):
        pytest.skip("both 2000 ΔT anchors required for the rate check")

    published_rate = end["value"] - start["value"]
    engine_rate = (swe.deltat(end["jd_ut"]) - swe.deltat(start["jd_ut"])) * 86400.0
    # Each endpoint carries its own uncertainty; a difference carries both.
    tol = sum(a["uncertainty"] + a["engine_allowance"] for a in (start, end))
    assert abs(engine_rate - published_rate) <= tol, (
        f"ΔT drift across 2000: engine {engine_rate:+.4f} s vs published "
        f"{published_rate:+.4f} s (tolerance ±{tol} s)"
    )


# --------------------------------------------------------------------------- #
# Planetary longitudes — where the engine actually puts a body
# --------------------------------------------------------------------------- #

_LONGITUDES = _load(LONGITUDES_FILE) if LONGITUDES_FILE.exists() else {"anchors": []}
_SWE_ID = {name: swe_id for name, swe_id, _ in _PLANET_TABLE}


def test_longitude_anchor_frame_is_of_date():
    """Assert the FRAME before asserting any value.

    ACQUISITION.md §1 calls this the frame trap: an anchor pulled in the J2000
    ecliptic instead of the ecliptic of date is wrong by up to ~1.4°/century of
    precession — two to three degrees at this file's 1800 and 2100 epochs. It
    fails as a smooth trend across epochs rather than as noise, which reads
    convincingly like an engine bug and would send someone hunting in the wrong
    place. Cheap to assert, expensive to debug.
    """
    if not _LONGITUDES["anchors"]:
        pytest.skip("planet_longitudes.json not acquired — see ACQUISITION.md")
    assert re.search(r"of date", _LONGITUDES.get("frame", ""), re.I), (
        "anchor frame must be the true ecliptic and equinox OF DATE — the frame "
        "swe_calc_ut returns. See ACQUISITION.md §Frame trap."
    )


@pytest.mark.parametrize("anchor", _LONGITUDES["anchors"], ids=lambda a: a["id"])
def test_planet_longitude_matches_published_ephemeris(anchor):
    """swe.calc_ut must put each body where JPL Horizons puts it.

    This is the first anchor in the directory that constrains a POSITION. ΔT
    pins the clock and ayanamsa.json pins the sidereal rotation, but neither
    says where a planet is. Nothing inside the repository can: the golden
    vectors are generated from the backend's own output, and the property
    harness compares the two engines to each other — both stay green if both
    are wrong together, which is a live risk now that both sit on Swiss.
    """
    swe_id = _SWE_ID.get(anchor["body"])
    assert swe_id is not None, (
        f"{anchor['id']}: {anchor['body']} is not in the app's _PLANET_TABLE"
    )
    with swe_lock:
        values, _ = swe.calc_ut(anchor["jd_ut"], swe_id, _FLG_LON)
    actual = values[0]
    tol = anchor["uncertainty"] + anchor["engine_allowance"]
    delta = _angular_sep(actual, anchor["value"])
    assert delta <= tol, (
        f"{anchor['id']}: engine {actual:.7f}° vs published {anchor['value']}° "
        f"(Δ{delta * 3600:.3f}\" > {tol * 3600:.3f}\" tolerance)\n"
        f"  frame:  {_LONGITUDES.get('frame', '?')[:60]}...\n"
        f"  source: {anchor['source']}\n"
        f"  {anchor['url']}\n"
        "  A miss that GROWS with distance from 2000 is a frame error, not a\n"
        "  position error — check the frame assertion above first.\n"
        "  Do NOT widen the anchor to make this pass — see parity/anchors/README.md."
    )


# --------------------------------------------------------------------------- #
# Ayanamsa — the sidereal frame's single degree of freedom
# --------------------------------------------------------------------------- #

_AYANAMSA = _load(AYANAMSA_FILE) if AYANAMSA_FILE.exists() else {"anchors": []}


def _ayanamsa_deg(jd_tt: float, frame: str) -> float:
    """Swiss Ephemeris' Lahiri ayanamsa at a TT instant, in the requested frame.

    Two things here are deliberate and both are frame decisions, not style:

    `FLG_NONUT` is what separates MEAN from TRUE. Without it Swiss returns the
    TRUE ayanamsa, which differs from the mean by nutation in longitude — up to
    ~17 arcsec, an order of magnitude larger than any tolerance in this file.
    The two anchors genuinely differ in frame because their sources do, so the
    flag is chosen per anchor rather than fixed here; a comparison that picked
    the wrong one would fail confidently while both engine and anchor were right.

    `get_ayanamsa_ex` (not `..._ex_ut`) takes a TT argument, matching the
    anchors' `jd_tt`. Going through the UT variant would apply ΔT twice over —
    negligible at J2000 (~1e-4 arcsec), less so the further out an anchor sits.
    """
    if frame not in ("mean", "true"):
        raise ValueError(
            f"unknown ayanamsa frame {frame!r} — the anchor's `frame` field must "
            "be 'mean' or 'true'. Guessing here is how a 17 arcsec nutation error "
            "gets mistaken for an engine bug."
        )
    flags = swe.FLG_NONUT if frame == "mean" else 0
    with swe_lock:
        swe.set_sid_mode(swe.SIDM_LAHIRI, 0, 0)
        out = swe.get_ayanamsa_ex(jd_tt, flags)
    # pyswisseph has returned both a bare float and a (retflag, ayanamsa) tuple
    # across versions; the repo pins 2.10 but the suite should not break on a
    # bump that only changes the wrapper's shape.
    return float(out[1]) if isinstance(out, (tuple, list)) else float(out)


@pytest.mark.parametrize("anchor", _AYANAMSA["anchors"], ids=lambda a: a["id"])
def test_ayanamsa_matches_published_value(anchor):
    """swe must reproduce the published Lahiri ayanamsa within the declared window.

    This is a rigid-rotation fault class. An ayanamsa error moves every body in
    a sidereal chart by exactly the same angle, so every aspect, pattern and
    inter-body relationship survives intact while signs and houses shift
    wholesale. Both engines rotate together, so the golden vectors stay green
    and the parity harness stays green — nothing inside this repository can see
    it. Only an external value can.
    """
    actual = _ayanamsa_deg(anchor["jd_tt"], anchor["frame"])
    tol = anchor["uncertainty"] + anchor["engine_allowance"]
    delta = abs(actual - anchor["value"])
    assert delta <= tol, (
        f"{anchor['id']}: engine {actual:.7f}° vs published {anchor['value']}° "
        f"(Δ{delta * 3600:.3f}\" > {tol * 3600:.3f}\" tolerance)\n"
        f"  frame:  {anchor['frame']}\n"
        f"  source: {anchor['source']}\n"
        f"  {anchor['url']}\n"
        "  Before touching the anchor, check the FRAME. A miss in the 14-17 arcsec\n"
        "  range is the nutation term — a mean-vs-true mix-up, not an engine error.\n"
        "  See the file's frame_note.\n"
        "  Do NOT widen the anchor to make this pass — see parity/anchors/README.md."
    )


def test_ayanamsa_mean_and_true_differ_by_nutation():
    """Guard the FRAME itself, which is the trap this anchor is most exposed to.

    The anchor is a MEAN value and the assertion above suppresses nutation to
    match it. If a future change swapped the flag — or if a Swiss bump altered
    what `FLG_NONUT` means — the anchor test could keep passing against the
    wrong quantity only if mean and true happened to coincide, which they do
    twice per 18.6-year nutation cycle. Asserting that the two are SEPARATED by
    a plausible nutation at an epoch where nutation is known to be large keeps
    that coincidence from being mistaken for correctness.

    This is engine-vs-engine and so is NOT an anchor assertion; it pins the
    frame, and the anchor pins the value.
    """
    if not _AYANAMSA["anchors"]:
        pytest.skip("no ayanamsa anchors acquired yet")
    jd_tt = _AYANAMSA["anchors"][0]["jd_tt"]
    diff_arcsec = (
        _ayanamsa_deg(jd_tt, "true") - _ayanamsa_deg(jd_tt, "mean")
    ) * 3600.0

    # Nutation in longitude is bounded by roughly ±17.2". At J2000 it is close
    # to −14"; the window is kept wide because this guards a frame, not a value.
    assert 0.5 <= abs(diff_arcsec) <= 20.0, (
        f"mean and true ayanamsa differ by {diff_arcsec:+.3f}\", which is not a "
        "plausible nutation in longitude. Either FLG_NONUT no longer suppresses "
        "nutation in this Swiss build, or both calls are now returning the same "
        "frame — in which case test_ayanamsa_matches_published_value is no longer "
        "checking what it claims to check."
    )


# --------------------------------------------------------------------------- #
# Provenance — the anchors' own contract, enforced
# --------------------------------------------------------------------------- #

ANCHOR_FILES = sorted(ANCHOR_DIR.glob("*.json"))

REQUIRED_FIELDS = (
    "id", "value", "unit", "uncertainty", "uncertainty_basis",
    "engine_allowance", "engine_allowance_note",
    "source", "url", "citation", "retrieved",
)


@pytest.mark.parametrize("path", ANCHOR_FILES, ids=lambda p: p.name)
def test_every_anchor_carries_full_provenance(path):
    """An anchor without provenance is just a number somebody typed.

    The directory's promise is that a third party can re-derive every value
    from its recorded source; that promise is only as good as the weakest
    record, so this is asserted mechanically rather than trusted to review.
    """
    payload = json.loads(path.read_text())
    assert payload.get("schema", "").startswith("astra-parity/anchor-"), (
        f"{path.name}: missing or malformed schema tag"
    )
    for anchor in payload["anchors"]:
        missing = [f for f in REQUIRED_FIELDS if f not in anchor]
        assert not missing, f"{path.name}:{anchor.get('id', '?')} missing {missing}"
        assert anchor["url"].startswith("http"), (
            f"{path.name}:{anchor['id']} url is not a retrievable reference"
        )
        assert anchor["citation"].strip(), (
            f"{path.name}:{anchor['id']} citation is empty — the quoted source "
            "text is what makes the value checkable by a third party"
        )


@pytest.mark.parametrize("path", ANCHOR_FILES, ids=lambda p: p.name)
def test_anchor_tolerances_stay_bounded(path):
    """A ratchet on the anchors themselves.

    The failure mode this exists for is a future session quietly multiplying
    an `engine_allowance` until a divergence fits inside it. An allowance
    wider than this could hide a chart-visible error, which is the one thing
    an anchor must never do.
    """
    limits = {
        # 0.5 s of ΔT ≈ 0.27 arcsec of lunar motion — still an order of
        # magnitude below the 0.01° tolerance any chart output is held to.
        "delta_t_seconds": 0.5,
        # 1 arcmin: the point at which a longitude error becomes capable of
        # flipping a sign or house assignment.
        "ecliptic_longitude_deg": 1.0 / 60.0,
        # Same 1 arcmin cap, same reason, but it bites harder: the ayanamsa is
        # a rigid rotation, so this error does not average out across a chart —
        # every body carries the full amount in the same direction at once.
        "ayanamsa_deg": 1.0 / 60.0,
    }
    payload = json.loads(path.read_text())
    cap = limits.get(payload["quantity"])
    if cap is None:
        pytest.skip(f"no declared cap for quantity {payload['quantity']}")
    for anchor in payload["anchors"]:
        total = anchor["uncertainty"] + anchor["engine_allowance"]
        assert total <= cap, (
            f"{path.name}:{anchor['id']} tolerance {total} exceeds the {cap} "
            f"{anchor['unit']} cap for {payload['quantity']} — a tolerance this "
            "wide could hide a chart-visible error. Justify it in an ADR under "
            "docs/design/adr/ and raise the cap deliberately, or fix the engine."
        )
