"""
Track A3 — the backend asserted against EXTERNAL ground truth.

`parity/*.json` proves the two engines agree; it cannot prove either is right,
because `gen_parity_vectors.py` writes the backend's own output and so makes
the backend an unfalsifiable oracle. A backend regression regenerates the
vectors and CI stays green.

`parity/anchors/` breaks that circle: values published outside this repository,
checked in, never regenerated by anything here. This suite asserts the BACKEND
against them. `packages/astra-core/test/anchors.test.ts` asserts the TS engine
against the same files independently — neither engine is the other's reference
here, which is the whole point.

Tolerance is `uncertainty + engine_allowance`, both read from the anchor
record. Widening either is an anchor change and trips the CI guard.
"""
import json
import os
import sys
from pathlib import Path

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import swisseph as swe  # noqa: E402

ANCHOR_DIR = Path(__file__).resolve().parents[2] / "parity" / "anchors"
DELTA_T_FILE = ANCHOR_DIR / "delta_t.json"


def _load(path: Path):
    if not path.exists():
        pytest.skip(f"{path.name} not acquired yet — see parity/anchors/ACQUISITION.md")
    return json.loads(path.read_text())


# --------------------------------------------------------------------------- #
# ΔT — the time base under every position in both engines
# --------------------------------------------------------------------------- #

_DELTA_T = _load(DELTA_T_FILE) if DELTA_T_FILE.exists() else {"anchors": []}


@pytest.mark.parametrize(
    "anchor", _DELTA_T["anchors"], ids=lambda a: a["id"]
)
def test_delta_t_matches_published_value(anchor):
    """swe.deltat() must reproduce the published ΔT within the source's own
    uncertainty plus the declared engine allowance.

    This is the fault class the golden vectors are structurally blind to: a
    wrong ΔT moves every body in BOTH engines identically, so they keep
    agreeing with each other while both drift away from the sky.
    """
    # swe.deltat returns DAYS; the anchor is published in seconds.
    actual = swe.deltat(anchor["jd_ut"]) * 86400.0
    tol = anchor["uncertainty"] + anchor["engine_allowance"]
    delta = abs(actual - anchor["value"])
    assert delta <= tol, (
        f"{anchor['id']}: engine {actual:.4f} s vs published {anchor['value']} s "
        f"(Δ{delta:.4f} s > {tol} s tolerance)\n"
        f"  source: {anchor['source']}\n"
        f"  {anchor['url']}\n"
        "  Do NOT widen the anchor to make this pass — see parity/anchors/README.md."
    )


def test_delta_t_rate_between_anchors():
    """Two ΔT points a year apart also pin the table's SLOPE.

    A constant offset bug and a rate bug both move a single point; only the
    pair separates them. Guarded so it degrades to a skip rather than an
    error if the anchor set is ever reduced to one point.
    """
    by_id = {a["id"]: a for a in _DELTA_T["anchors"]}
    start, end = by_id.get("deltat-2000-01-01"), by_id.get("deltat-2000-12-31")
    if not (start and end):
        pytest.skip("both 2000 ΔT anchors required for the rate check")

    published_rate = end["value"] - start["value"]
    engine_rate = (swe.deltat(end["jd_ut"]) - swe.deltat(start["jd_ut"])) * 86400.0
    # Each endpoint carries its own uncertainty; a difference carries both.
    tol = sum(a["uncertainty"] + a["engine_allowance"] for a in (start, end))
    assert abs(engine_rate - published_rate) <= tol, (
        f"ΔT drift across 2000: engine {engine_rate:+.4f} s vs published "
        f"{published_rate:+.4f} s (tolerance ±{tol} s)"
    )


# --------------------------------------------------------------------------- #
# Provenance — the anchors' own contract, enforced
# --------------------------------------------------------------------------- #

ANCHOR_FILES = sorted(ANCHOR_DIR.glob("*.json"))

REQUIRED_FIELDS = (
    "id", "value", "unit", "uncertainty", "uncertainty_basis",
    "engine_allowance", "engine_allowance_note",
    "source", "url", "citation", "retrieved",
)


@pytest.mark.parametrize("path", ANCHOR_FILES, ids=lambda p: p.name)
def test_every_anchor_carries_full_provenance(path):
    """An anchor without provenance is just a number somebody typed.

    The directory's promise is that a third party can re-derive every value
    from its recorded source; that promise is only as good as the weakest
    record, so this is asserted mechanically rather than trusted to review.
    """
    payload = json.loads(path.read_text())
    assert payload.get("schema", "").startswith("astra-parity/anchor-"), (
        f"{path.name}: missing or malformed schema tag"
    )
    for anchor in payload["anchors"]:
        missing = [f for f in REQUIRED_FIELDS if f not in anchor]
        assert not missing, f"{path.name}:{anchor.get('id', '?')} missing {missing}"
        assert anchor["url"].startswith("http"), (
            f"{path.name}:{anchor['id']} url is not a retrievable reference"
        )
        assert anchor["citation"].strip(), (
            f"{path.name}:{anchor['id']} citation is empty — the quoted source "
            "text is what makes the value checkable by a third party"
        )


@pytest.mark.parametrize("path", ANCHOR_FILES, ids=lambda p: p.name)
def test_anchor_tolerances_stay_bounded(path):
    """A ratchet on the anchors themselves.

    The failure mode this exists for is a future session quietly multiplying
    an `engine_allowance` until a divergence fits inside it. An allowance
    wider than this could hide a chart-visible error, which is the one thing
    an anchor must never do.
    """
    limits = {
        # 0.5 s of ΔT ≈ 0.27 arcsec of lunar motion — still an order of
        # magnitude below the 0.01° tolerance any chart output is held to.
        "delta_t_seconds": 0.5,
        # 1 arcmin: the point at which a longitude error becomes capable of
        # flipping a sign or house assignment.
        "ecliptic_longitude_deg": 1.0 / 60.0,
    }
    payload = json.loads(path.read_text())
    cap = limits.get(payload["quantity"])
    if cap is None:
        pytest.skip(f"no declared cap for quantity {payload['quantity']}")
    for anchor in payload["anchors"]:
        total = anchor["uncertainty"] + anchor["engine_allowance"]
        assert total <= cap, (
            f"{path.name}:{anchor['id']} tolerance {total} exceeds the {cap} "
            f"{anchor['unit']} cap for {payload['quantity']} — a tolerance this "
            "wide could hide a chart-visible error. Justify it in an ADR under "
            "docs/design/adr/ and raise the cap deliberately, or fix the engine."
        )
