// Landing-page service worker: the offline surprise.
//
// astra-arcana.com is a static pitch. Offline it has nothing to say, and the
// browser shows its own error page — so this precaches TAPBLADE and serves it
// when a navigation fails. Same move as Chrome's dinosaur, on a page that
// otherwise had nothing to offer.
//
// Scope note: this worker is registered from the landing origin only. The PWA
// at app.astra-arcana.com has its OWN, unrelated service worker, generated by
// vite-plugin-pwa. Two different origins, two workers, no interaction — which
// is one more reason the two-origin split was worth the extra DNS record.
const CACHE = "astra-offline-v1";

// Only what the fallback needs. Deliberately NOT the landing page itself: if
// index.html were cached, an offline visit would get a stale pitch instead of
// the game, which is the opposite of the intent. The pitch is worth nothing
// offline anyway — every link on it goes somewhere unreachable.
const ASSETS = [
  "/tapblade/",
  "/tapblade/tapblade.css",
  "/tapblade/tapblade.js",
];

self.addEventListener("install", (event) => {
  // skipWaiting so a returning visitor gets the current worker immediately
  // rather than after closing every tab. There is no cross-version state here
  // to corrupt: the cache holds three static files.
  event.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;

  // Game assets: cache-first, so the fallback cannot itself fail offline.
  if (new URL(request.url).pathname.startsWith("/tapblade/")) {
    event.respondWith(caches.match(request).then((hit) => hit || fetch(request)));
    return;
  }

  // Everything else: network-first. NOTE the check is `mode === "navigate"`,
  // not `destination === "document"` — a fetch() for an HTML fragment is also
  // a document, and answering that with a full game page would be nonsense.
  // Only a real page navigation earns the fallback.
  if (request.mode === "navigate") {
    event.respondWith(
      // `cache: "no-store"` is load-bearing, and its absence is invisible in
      // testing unless you check the exact case. nginx sends no Cache-Control
      // for the landing HTML, so the browser heuristically caches it; a plain
      // fetch(request) while offline is then answered FROM THAT CACHE, resolves
      // successfully, and .catch() never runs. The fallback appeared to work
      // only for URLs never visited before — i.e. it would have failed for
      // exactly the returning visitors who have a worker installed at all.
      //
      // fetch(url) rather than fetch(request): a navigate-mode Request cannot
      // be reconstructed with different options, and this host serves one
      // static page with no redirects or credentials, so a plain same-origin
      // GET carries everything that matters.
      fetch(request.url, { cache: "no-store" }).catch(() =>
        caches.match("/tapblade/").then(
          (hit) =>
            hit ||
            // The cache should always hold it, but a Response is required here:
            // returning undefined surfaces as an opaque network error, which
            // would look like the worker is broken rather than the network.
            new Response("<h1>Offline</h1>", {
              status: 503,
              headers: { "Content-Type": "text/html; charset=utf-8" },
            })
        )
      )
    );
  }
});
