// The TS side of the drift lock: reproduce parity/natal-chart.json within the
// tolerance contract stored in the file. The vectors were generated by the
// Python backend (pyswisseph/Moshier); @astra/core runs astronomy-engine, a
// DIFFERENT Moshier-class implementation, so angular fields use the parity
// README's cross-engine widening (×5). Exact fields stay exact.
//
// Full body coverage: North/South Node, Chiron and Lilith ride the vendored
// WASM Swiss engine (initSwisseph below) — the SUPPORTED filter now spans the
// whole backend body set and is kept only so a future body addition can start
// restricted until its TS engine lands.

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

import { angularSeparation, calculateChart } from "../src/index.js";

import { initSwisseph } from "../src/swisseph.js";

// The extended bodies (Node/Chiron/Lilith) ride the WASM Swiss engine.
await initSwisseph();

const here = path.dirname(fileURLToPath(import.meta.url));
const payload = JSON.parse(
  readFileSync(path.join(here, "../../../parity/natal-chart.json"), "utf8")
);

const TOL = payload.tolerances as Record<string, number>;
// Both stacks now run the SAME Swiss C code on the same seas-only data — the
// old ×5 cross-engine widening collapses. 1e-6 covers the vector's 6-dp float
// rounding; the contract tolerances in the file stay as the outer bound.
const CROSS = 1;
const EXACTISH = 1e-6;

const SUPPORTED = new Set([
  "Sun", "Moon", "Mercury", "Venus", "Mars", "Jupiter", "Saturn",
  "Uranus", "Neptune", "Pluto", "North Node", "South Node", "Chiron",
  "Lilith", "Part of Fortune", "Ascendant", "Midheaven",
]);

// Aspect-set membership flips when an orb sits within the cross-engine noise
// of an aspect family's cutoff; such borderline pairs are tolerated (only) in
// the symmetric difference.
const BOUNDARY_MARGIN = TOL["planet.longitude_deg"] * CROSS * 2;

const aspectKey = (a: any) =>
  [...[a.p1, a.p2].sort(), a.type].join("|");
const patternKey = (p: any) =>
  `${p.type}:${[...p.planets].sort().join(",")}`;

for (const kase of payload.cases) {
  test(`parity: ${kase.id}`, () => {
    const actual = calculateChart(kase.request);
    const expected = kase.expected;
    const deltas: string[] = [];

    // Julian day — pure arithmetic, engine-independent.
    assert.ok(
      Math.abs(Number(actual.meta.julian_day) - Number(expected.meta.julian_day)) <= 1e-6,
      `julian_day: ${actual.meta.julian_day} vs ${expected.meta.julian_day}`
    );

    // Planets (supported subset — none missing, none extra).
    const expPlanets = new Map<string, any>(
      expected.planets.filter((p: any) => SUPPORTED.has(p.id)).map((p: any) => [p.id, p])
    );
    const actPlanets = new Map(actual.planets.map((p) => [p.id, p]));
    assert.deepEqual([...actPlanets.keys()].sort(), [...expPlanets.keys()].sort());

    for (const [pid, ep] of expPlanets) {
      const ap = actPlanets.get(pid)!;
      const dLon = angularSeparation(ap.longitude, ep.longitude);
      deltas.push(`${pid} Δlon=${dLon.toFixed(5)}`);
      assert.ok(dLon <= EXACTISH, `${pid} lon Δ${dLon}`);
      assert.ok(
        Math.abs(ap.latitude - ep.latitude) <= EXACTISH,
        `${pid} lat ${ap.latitude} vs ${ep.latitude}`
      );
      assert.ok(
        Math.abs(ap.declination - ep.declination) <= EXACTISH,
        `${pid} dec ${ap.declination} vs ${ep.declination}`
      );
      assert.ok(
        Math.abs(ap.speed - ep.speed) <= EXACTISH,
        `${pid} speed ${ap.speed} vs ${ep.speed}`
      );
      for (const f of ["sign", "house", "retrograde", "dignity", "element", "modality"] as const) {
        assert.equal(ap[f], ep[f], `${pid}.${f}`);
      }
      // degree can flip at a sign boundary within tolerance — compare via sign+degree
      // only when the longitude sits clear of a whole-degree edge.
      const within = ep.longitude % 1;
      if (within > 0.02 && within < 0.98) {
        assert.equal(ap.degree, ep.degree, `${pid}.degree`);
      }
    }

    // House cusps + angles.
    for (let i = 0; i < 12; i++) {
      const d = angularSeparation(actual.houses[i].longitude, expected.houses[i].longitude);
      deltas.push(`H${i + 1} Δ=${d.toFixed(5)}`);
      assert.ok(d <= EXACTISH, `house ${i + 1} Δ${d}`);
    }
    for (const name of ["ascendant", "midheaven", "descendant", "imum_coeli"] as const) {
      const d = angularSeparation(actual.angles[name], expected.angles[name]);
      assert.ok(d <= EXACTISH, `${name} Δ${d}`);
    }

    // Aspects among supported bodies: sets must match modulo boundary flips.
    const expAspects = new Map<string, any>(
      expected.aspects
        .filter((a: any) => SUPPORTED.has(a.p1) && SUPPORTED.has(a.p2))
        .map((a: any) => [aspectKey(a), a] as [string, any])
    );
    const actAspects = new Map<string, any>(
      actual.aspects.map((a) => [aspectKey(a), a] as [string, any])
    );
    const onlyExp = [...expAspects.keys()].filter((k) => !actAspects.has(k));
    const onlyAct = [...actAspects.keys()].filter((k) => !expAspects.has(k));
    for (const k of onlyExp) {
      const a: any = expAspects.get(k);
      const def = a.orb;
      assert.ok(
        Math.abs(def - maxOrbFor(a.type)) <= BOUNDARY_MARGIN,
        `missing aspect not at boundary: ${k} (orb ${a.orb})`
      );
    }
    for (const k of onlyAct) {
      const a: any = actAspects.get(k);
      assert.ok(
        Math.abs(a.orb - maxOrbFor(a.type)) <= BOUNDARY_MARGIN,
        `extra aspect not at boundary: ${k} (orb ${a.orb})`
      );
    }
    for (const [k, ea] of expAspects) {
      const aa = actAspects.get(k);
      if (!aa) continue;
      assert.ok(
        Math.abs(aa.orb - (ea as any).orb) <= TOL["aspect.orb_deg"] * CROSS * 2,
        `${k} orb ${aa.orb} vs ${(ea as any).orb}`
      );
    }

    // Patterns whose members are all supported must match exactly.
    const expPatterns = new Set(
      expected.patterns
        .filter((p: any) => p.planets.every((x: string) => SUPPORTED.has(x)))
        .map(patternKey)
    );
    const actPatterns = new Set(actual.patterns.map(patternKey));
    assert.deepEqual([...actPatterns].sort(), [...expPatterns].sort());

    // Weighted tallies are exact (their counted set is fully supported).
    assert.deepEqual(actual.elements, expected.elements);
    assert.deepEqual(actual.modalities, expected.modalities);

    console.log(`  [${kase.id}] max deltas → ${topDeltas(deltas, 5).join("  ")}`);
  });
}

function maxOrbFor(type: string): number {
  const orbs: Record<string, number> = {
    Conjunction: 8, Opposition: 8, Trine: 7, Square: 6, Sextile: 5,
    Quincunx: 3, Semisextile: 2, Sesquiquadrate: 2, Semisquare: 2, Quintile: 2,
  };
  return orbs[type];
}

function topDeltas(deltas: string[], n: number): string[] {
  return deltas
    .map((s) => ({ s, v: Number(s.split("=")[1]) }))
    .sort((a, b) => b.v - a.v)
    .slice(0, n)
    .map((x) => x.s);
}
